### ISSUE TITLE
Issue in config/setup

### ISSUE THREAD

**Issue by TheChuckMo** [genebean/genebean-networker#6]
I think I am having a problem with setup, of course I believe I have it right, but I am getting an error that I think is related to connection ports. 

My Setup
- Redhat Satelite 6 as ENC
- Puppet running with SAT6
- networker module installed 
  - variables set via SAT6 as an ENC

First attempt I only set the NSR server name (all I need for clients), but getting the error below I also set the connection port range hoping that would help. 

Below is the error I am getting: 

> Error: Could not apply complete catalog: Found 1 dependency cycle:
> (Exec[set_nsr_connectionports] => Class[Networker::Config] => Class[Networker::Service] => Service[networker] => Exec[set_nsr_connectionports])
> Try the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz

Any suggestions would are greatly appreciated.

**Comment by genebean** [comment]
Sorry for the delay in getting to this, I am looking into it now.

**Comment by TheChuckMo** [comment]
No problem at all. I'm sure it's my setup, new to puppet and satelite.   Thanks, Chuck

**Comment by genebean** [comment]
It turned out that the way ports were being set created a circular dependency with the service. I have resolved this and will push a new version to the forge in a few minutes.

**Comment by TheChuckMo** [comment]
Thank you!
